nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:4200'] # Cambia esto por el dominio de tu frontend
        allow_credentials: true
        allow_headers: ['content-type', 'authorization']
        expose_headers: ['link']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        max_age: 3600
    paths:
        '^/': # Esto aplica las reglas a todas las rutas
            allow_origin: ['http://localhost:4200']